# Generated by Django 3.0.4 on 2020-05-19 14:07

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_upload_path, verbose_name='Profile picture'),
        ),
    ]
