# Generated by Django 3.0.4 on 2020-06-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userml_uservisithistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserML',
            new_name='UserMLData',
        ),
    ]
