# Generated by Django 3.0.4 on 2020-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_amount_to_be_raised'),
        ('accounts', '0004_auto_20200617_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('validity_start_date', models.DateTimeField(verbose_name='Validity start date')),
                ('validity_end_date', models.DateTimeField(verbose_name='Validity end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='organizations.Organization', verbose_name='Organization')),
            ],
        ),
    ]
