# Generated by Django 3.0.4 on 2020-06-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('organizations', '0004_organization_amount_to_be_raised'),
        ('accounts', '0006_coupon_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='UserCoupon',
        ),
    ]
