# Generated by Django 3.0.4 on 2020-06-18 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='mobile_number',
        ),
    ]
