# Generated by Django 3.0.4 on 2020-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_organization_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='amount_to_be_raised',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount to be raised?'),
            preserve_default=False,
        ),
    ]
